apiVersion: v1
kind: ConfigMap
metadata:
  name: desafio-nginx-conf
data:
  index.html: |
    
    <h1> Code.education Rocks. </h1>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: desafio-nginx
  template:
    metadata:
      labels:
        app: desafio-nginx
    spec:
      containers:
      - name: desafio-nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: desafio-nginx-conf
          readOnly: true
      
      volumes:
      - name: desafio-nginx-conf
        configMap:
          name: desafio-nginx-conf
          items:
            - key: index.html
              path: index.html


---

apiVersion: v1
kind: Service
metadata:
  name: desafio-nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: desafio-nginx